# Generated by Django 3.1.3 on 2020-11-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', '남성'), ('female', '여성')], max_length=10, null=True),
        ),
    ]
